_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  audiofield: 0
  automated_cron: 0
  big_pipe: 0
  blazy: 0
  blazy_ui: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  config_translation: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  dynamic_page_cache: 0
  editor: 0
  feeds: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  font_awesome: 0
  fontawesome: 0
  fontawesome_iconpicker_widget: 0
  fontawesome_media: 0
  fontawesome_menu_icons: 0
  help: 0
  history: 0
  iframe: 0
  image: 0
  intercom: 0
  language: 0
  link: 0
  locale: 0
  lp_fontawesome: 0
  media: 0
  menu_link_content: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  rdf: 0
  responsive_image: 0
  search: 0
  search_api: 0
  search_api_db: 0
  search_api_db_defaults: 0
  shortcut: 0
  slick: 0
  slick_ui: 0
  slick_views: 0
  social_api: 0
  social_auth: 0
  svg_image: 0
  svg_image_responsive: 0
  system: 0
  taxonomy: 0
  tb_megamenu: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_ui: 0
  fontyourface: 1
  pathauto: 1
  content_translation: 10
  fontscom_api: 10
  google_fonts_api: 10
  views: 10
  standard: 1000
theme:
  bartik: 0
  seven: 0
  stable: 0
  the_wire: 0
profile: standard
